// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYNCwa3DL5c4goFob-SzC-gUsJ02Acxpc',
    appId: '1:440988943055:web:a645e911c0d6fa47d26dba',
    messagingSenderId: '440988943055',
    projectId: 'alimi-pro-2-3b2fb',
    authDomain: 'alimi-pro-2-3b2fb.firebaseapp.com',
    databaseURL: 'https://alimi-pro-2-3b2fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alimi-pro-2-3b2fb.appspot.com',
    measurementId: 'G-6GY7YNSWG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBTwkTwO0A6OSWA9eS0tkvSmtvgEo-KU',
    appId: '1:440988943055:android:a76657905ed9ff53d26dba',
    messagingSenderId: '440988943055',
    projectId: 'alimi-pro-2-3b2fb',
    databaseURL: 'https://alimi-pro-2-3b2fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alimi-pro-2-3b2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-pXskXOWqcC9a6N-K0HUzlqoaAv0lLF8',
    appId: '1:440988943055:ios:ece8070066c49129d26dba',
    messagingSenderId: '440988943055',
    projectId: 'alimi-pro-2-3b2fb',
    databaseURL: 'https://alimi-pro-2-3b2fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alimi-pro-2-3b2fb.appspot.com',
    iosClientId: '440988943055-8qhasu1f0de9662a4c8bii4jarp6hmai.apps.googleusercontent.com',
    iosBundleId: 'com.survivalcoding.alimiproMockData',
  );

}